// FILE PATH: frontend/src/context/LanguageContext.jsx
import React, { createContext, useState, useContext } from 'react';
import { STORAGE_KEYS } from '../utils/constants';

const commonKeys = {
    title: "IAP-MG Using GenAI",
    welcomeBack: "Welcome Back", createAccount: "Create Your Account",
    fullName: "Full Name", email: "Email", phone: "Phone Number", password: "Password",
    confirmPassword: "Confirm Password", age: "Age", dob: "Date of Birth", gender: "Gender",
    preferredLanguage: "Preferred Language", bloodGroup: "Blood Group",
    medicalConditions: "Existing Medical Conditions",
    register: "Register", login: "Login", logout: "Logout", otp: "OTP",
    resetPassword: "Reset Password", forgotPassword: "Forgot Password?",
    welcomeBackUser: "Welcome back, {name}", startNewDiagnosis: "Start New Diagnosis",
    totalSessions: "Total Sessions", completed: "Completed", language: "Language",
    recentSessions: "Recent Diagnosis Sessions", historyDesc: "Your health assessment history",
    noSessions: "No diagnosis sessions yet",
    startFirst: "Start your first health assessment to see it here",
    deleteConfirm: "Delete Diagnosis?",
    areYouSureDelete: "Are you sure you want to delete this session?",
    permanentAction: "This action cannot be undone. All data will be permanently deleted.",
    settings: "Settings", changeLanguage: "Change Language",
    confirmLanguageChange: "Confirm Language Change",
    languageChangeCheck: "Are you sure you want to change the application language to",
    cancel: "Cancel", confirm: "Confirm", delete: "Delete", view: "View",
    readyToStart: "Ready to start a new health assessment today?",
    syncingHealthData: "Syncing Health Data...", analysisPending: "Analysis Pending",
    noSymptomsRecorded: "No symptoms recorded",
    sessionDeletedSuccessfully: "Session deleted successfully",
    sessionRemoved: "Session removed", languageUpdated: "Language updated to {lang}",
    failedToUpdateLanguage: "Failed to update language",
    somethingWentWrong: "Something went wrong",
    pending: "Pending", emergency: "Emergency", analyzing: "Analyzing",
    aiMedicalDiagnosis: "AI Medical Diagnosis",
    instantHealthAssessment: "Instant health assessment powered by Google Gemini AI",
    symptoms: "Symptoms", aiAnalysis: "AI Analysis",
    backToDashboard: "Back to Dashboard",
    diagnosisResults: "Diagnosis Results", sessionFrom: "Session from {date}",
    possibleConditions: "Possible Conditions",
    tellUsWhatYouFeel: "Tell Us What You're Feeling",
    describeSymptomsDetail: "Describe your symptoms in detail. Our AI will analyze and provide instant medical guidance.",
    describeSymptoms: "Describe your symptoms *",
    symptomsPlaceholder: "Example: I have been experiencing a persistent headache for 3 days, along with mild fever and body aches...",
    pleaseDescribeSymptoms: "Please describe your symptoms",
    moreDetailsRequired: "Please provide more details (at least 10 characters)",
    howLongSymptoms: "How long have you had these symptoms?", selectDuration: "Select duration",
    howSevere: "How severe are your symptoms?", selectSeverity: "Select severity",
    tipTitle: "Tip:",
    symptomTip: "Be as specific as possible. Mention when symptoms started, any triggers, patterns, or related symptoms you've noticed.",
    quickExamples: "Quick examples:", getAiDiagnosis: "Get AI Diagnosis",
    analyzingSymptoms: "Analyzing your symptoms...",
    aiAnalyzingSymptoms: "AI is analyzing your symptoms...",
    analysisFailed: "Analysis Failed", tryAgain: "Try Again",
    noDiagnosisAvailable: "No Diagnosis Available",
    startOver: "Start Over", yourAiDiagnosisResults: "Your AI Diagnosis Results",
    analysisPoweredBy: "Analysis powered by Google Gemini AI",
    mostLikely: "Most Likely", confidence: "Confidence",
    show: "Show", hide: "Hide", clinicalReasoning: "Clinical Reasoning",
    clickForBreakdown: "Click for details",
    confidenceBreakdown: "Confidence Breakdown",
    symptomMatch: "Symptom Match", severityAlignment: "Severity Alignment",
    durationCorrelation: "Duration Correlation",
    symptomMatchDesc: "How well your symptoms align with this condition",
    severityAlignmentDesc: "Symptom severity matches typical presentation",
    durationCorrelationDesc: "Timeline fits disease progression",
    clinicalReasoningDesc: "AI analysis of medical patterns",
    howWeCalculated: "How We Calculated This Score",
    overallScore: "Overall Confidence Score", closeBreakdown: "Close Breakdown",
    weight: "Weight", symptomRelief: "Symptom relief",
    scoreCalculationDesc: "AI analyzed 4 key factors with different weights to arrive at the final confidence score.",
    recommendedMedicines: "💊 Recommended Medicines",
    medicinesSubtitle: "Over-the-counter medications for symptom relief (information purpose only)",
    medicineDosage: "Dosage", medicineFrequency: "Frequency",
    medicineDuration: "Duration", medicineTiming: "Timing",
    medicineSideEffects: "Side Effects", medicineNo: "Medicine",
    otcWarning: "⚠️ Important: These are general OTC medication suggestions. Consult a pharmacist or doctor before taking any medication, especially if you have existing medical conditions or allergies.",
    dietRecommendations: "🥗 Diet Recommendations",
    dietSubtitle: "Foods that can help in recovery and those to avoid",
    foodsToEat: "Foods to Eat", foodsToAvoid: "Foods to Avoid",
    noSpecificRecommendations: "No specific recommendations",
    noSpecificRestrictions: "No specific restrictions",
    dietTip: "💡 Tip: Maintain a balanced diet with plenty of fluids. Individual dietary needs may vary based on allergies and existing conditions.",
    safetyPrecautions: "🛡️ Safety Precautions",
    precautionsSubtitle: "Important measures to follow for faster recovery",
    seekMedicalAttention: "⚠️ When to Seek Immediate Medical Attention:",
    warnSymptomsWorsen: "Symptoms worsen significantly",
    warnHighFever: "High fever persists for more than 3 days",
    warnBreathing: "Difficulty breathing or chest pain develops",
    warnDehydration: "Severe dehydration or inability to keep fluids down",
    warnSuddenChange: "Any sudden or concerning changes in condition",
    recoveryInformation: "⏱️ Recovery Information",
    recoverySubtitle: "Expected timeline and follow-up guidance",
    expectedRecovery: "Expected Recovery", recoveryOutlook: "Recovery Outlook",
    confidenceHigh: "Full recovery is expected with recommended treatment.",
    confidenceMedium: "Good recovery expected with proper care and monitoring.",
    confidenceLow: "Medical supervision may be needed for recovery.",
    recoveryTimeline: "Recovery Timeline",
    followUpRecommendations: "Follow-up Recommendations",
    mostPatientsRecover: "Most patients recover within this timeframe with proper care and rest.",
    medicalDisclaimer: "Medical Disclaimer",
    disclaimerText: "This is an AI-powered guidance system for educational purposes only. It is NOT a replacement for professional medical advice. Always consult a qualified healthcare provider.",
    downloadPDF: "Download PDF", emailReport: "Email Report", smsReminders: "SMS Reminders",
    generating: "Generating...", sending: "Sending...",
    reportSentTo: "Report sent to {email}!", downloadedSuccessfully: "PDF downloaded successfully!",
    sessionNotFound: "Session Not Found", unableToLoadSession: "Unable to load diagnosis session",
    scheduling: "Scheduling...", scheduleReminders: "Schedule Reminders",
    phoneError: "Please enter phone number", medicineError: "Please enter medicine name",
    dateError: "Please select follow-up date", typeError: "Please select reminder type",
    dur_less24h: "Less than 24 hours", dur_1_3d: "1-3 days", dur_3_7d: "3-7 days",
    dur_1_2w: "1-2 weeks", dur_more2w: "More than 2 weeks",
    sev_mild: "Mild", sev_moderate: "Moderate", sev_severe: "Severe",
    ex_fever: "Fever, headache, body aches", ex_cough: "Cough, sore throat, runny nose",
    ex_stomach: "Stomach pain, nausea, vomiting", ex_chest: "Chest pain, difficulty breathing",
};

const translations = {
    English: { ...commonKeys },

    Telugu: {
        ...commonKeys,
        title: "IAP-MG జెనరేటివ్ AI ఉపయోగించి",
        welcomeBack: "తిరిగి స్వాగతం", createAccount: "మీ ఖాతాను సృష్టించండి",
        fullName: "పూర్తి పేరు", email: "ఇమెయిల్", phone: "ఫోన్ నంబర్",
        password: "పాస్‌వర్డ్", confirmPassword: "పాస్‌వర్డ్ నిర్ధారించండి",
        register: "నమోదు చేయండి", login: "లాగిన్", logout: "లాగ్ అవుట్",
        welcomeBackUser: "తిరిగి స్వాగతం, {name}",
        startNewDiagnosis: "కొత్త రోగనిర్ధారణ ప్రారంభించండి",
        totalSessions: "మొత్తం సెషన్లు", completed: "పూర్తయింది", language: "భాష",
        recentSessions: "ఇటీవలి రోగనిర్ధారణ సెషన్లు",
        noSessions: "ఇంకా రోగనిర్ధారణ సెషన్లు లేవు",
        startFirst: "మీ మొదటి ఆరోగ్య అంచనా ప్రారంభించండి",
        settings: "సెట్టింగులు", changeLanguage: "భాష మార్చండి",
        cancel: "రద్దు చేయండి", confirm: "నిర్ధారించండి", delete: "తొలగించు", view: "చూడు",
        readyToStart: "ఈరోజు కొత్త ఆరోగ్య అంచనా ప్రారంభించాలా?",
        somethingWentWrong: "ఏదో తప్పు జరిగింది", pending: "పెండింగ్", emergency: "అత్యవసరం",
        aiMedicalDiagnosis: "AI వైద్య రోగనిర్ధారణ",
        instantHealthAssessment: "Google Gemini AI ద్వారా తక్షణ ఆరోగ్య అంచనా",
        symptoms: "లక్షణాలు", aiAnalysis: "AI విశ్లేషణ",
        backToDashboard: "డాష్‌బోర్డ్‌కు వెళ్ళు",
        diagnosisResults: "రోగనిర్ధారణ ఫలితాలు",
        possibleConditions: "సాధ్యమయ్యే పరిస్థితులు",
        tellUsWhatYouFeel: "మీకు ఎలా అనిపిస్తుందో చెప్పండి",
        describeSymptomsDetail: "మీ లక్షణాలను వివరంగా వివరించండి. మా AI విశ్లేషించి తక్షణ మార్గదర్శకత్వం అందిస్తుంది.",
        describeSymptoms: "మీ లక్షణాలు వివరించండి *",
        symptomsPlaceholder: "ఉదాహరణ: నాకు 3 రోజుల నుండి నిరంతర తలనొప్పి వస్తోంది...",
        tipTitle: "చిట్కా:", symptomTip: "వీలైనంత నిర్దిష్టంగా చెప్పండి.",
        quickExamples: "త్వరిత ఉదాహరణలు:", getAiDiagnosis: "AI రోగనిర్ధారణ పొందండి",
        analyzingSymptoms: "మీ లక్షణాలు విశ్లేషిస్తోంది...",
        analysisFailed: "విశ్లేషణ విఫలమైంది", tryAgain: "మళ్ళీ ప్రయత్నించు",
        yourAiDiagnosisResults: "మీ AI రోగనిర్ధారణ ఫలితాలు",
        analysisPoweredBy: "Google Gemini AI ద్వారా విశ్లేషణ",
        mostLikely: "అత్యంత సంభావ్యత", confidence: "నమ్మకం",
        show: "చూపించు", hide: "దాచు", clinicalReasoning: "క్లినికల్ రీజనింగ్",
        clickForBreakdown: "వివరాలకు క్లిక్ చేయండి",
        confidenceBreakdown: "నమ్మకం విభజన",
        symptomMatch: "లక్షణాల సరిపోలిక", severityAlignment: "తీవ్రత అమరిక",
        durationCorrelation: "వ్యవధి సహసంబంధం",
        symptomMatchDesc: "మీ లక్షణాలు ఈ పరిస్థితి లక్షణాలతో ఎంత సరిపోతున్నాయి",
        severityAlignmentDesc: "లక్షణాల తీవ్రత సాధారణ ప్రదర్శనతో సరిపోతుంది",
        durationCorrelationDesc: "వ్యవధి వ్యాధి పురోగతితో సరిపోతుంది",
        clinicalReasoningDesc: "వైద్య నమూనాల AI విశ్లేషణ",
        howWeCalculated: "ఈ స్కోర్‌ను ఎలా లెక్కించాం",
        overallScore: "మొత్తం నమ్మకం స్కోర్",
        closeBreakdown: "మూసివేయి",
        weight: "బరువు", symptomRelief: "లక్షణాల ఉపశమనం",
        scoreCalculationDesc: "AI 4 కీలక కారకాలను విశ్లేషించి తుది స్కోర్ లెక్కించింది.",
        recommendedMedicines: "💊 సిఫార్సు చేయబడిన మందులు",
        medicinesSubtitle: "లక్షణాల ఉపశమనం కోసం OTC మందులు (సమాచార ప్రయోజనం మాత్రమే)",
        medicineDosage: "మోతాదు", medicineFrequency: "పౌనఃపున్యం",
        medicineDuration: "వ్యవధి", medicineTiming: "సమయం",
        medicineSideEffects: "దుష్ప్రభావాలు", medicineNo: "మందు",
        otcWarning: "⚠️ ముఖ్యం: ఇవి సాధారణ OTC మందుల సూచనలు. ఏ మందు తీసుకోవడానికి ముందు ఫార్మాసిస్ట్ లేదా వైద్యుడిని సంప్రదించండి, ముఖ్యంగా మీకు ఇప్పటికే అనారోగ్యాలు లేదా అలెర్జీలు ఉంటే.",
        dietRecommendations: "🥗 ఆహార సిఫార్సులు",
        dietSubtitle: "కోలుకోవడంలో సహాయపడే మరియు నివారించాల్సిన ఆహారాలు",
        foodsToEat: "తినాల్సిన ఆహారాలు", foodsToAvoid: "నివారించాల్సిన ఆహారాలు",
        noSpecificRecommendations: "నిర్దిష్ట సిఫార్సులు లేవు",
        noSpecificRestrictions: "నిర్దిష్ట నిషేధాలు లేవు",
        dietTip: "💡 చిట్కా: పుష్కలమైన ద్రవాలతో సమతుల్య ఆహారం తీసుకోండి. వ్యక్తిగత అవసరాలు అలెర్జీలను బట్టి మారవచ్చు.",
        safetyPrecautions: "🛡️ భద్రతా జాగ్రత్తలు",
        precautionsSubtitle: "వేగంగా కోలుకోవడానికి అనుసరించాల్సిన ముఖ్యమైన చర్యలు",
        seekMedicalAttention: "⚠️ వెంటనే వైద్య సహాయం ఎప్పుడు పొందాలి:",
        warnSymptomsWorsen: "లక్షణాలు గణనీయంగా తీవ్రమవుతాయి",
        warnHighFever: "అధిక జ్వరం 3 రోజుల కంటే ఎక్కువ కాలం కొనసాగుతుంది",
        warnBreathing: "శ్వాస తీసుకోవడంలో ఇబ్బంది లేదా ఛాతీ నొప్పి వస్తుంది",
        warnDehydration: "తీవ్రమైన నిర్జలీకరణం లేదా ద్రవాలు తీసుకోలేకపోవడం",
        warnSuddenChange: "ఆకస్మిక లేదా ఆందోళనకరమైన పరిస్థితిలో మార్పులు",
        recoveryInformation: "⏱️ కోలుకోవడపు సమాచారం",
        recoverySubtitle: "అంచనా వేళాపట్టి మరియు అనుసరణ మార్గదర్శకత్వం",
        expectedRecovery: "అంచనా వేసిన కోలుకోవడం", recoveryOutlook: "కోలుకోవడపు అవకాశం",
        confidenceHigh: "సిఫార్సు చేయబడిన చికిత్సతో పూర్తి కోలుకోవడం అంచనా.",
        confidenceMedium: "సరైన శ్రద్ధతో మంచి కోలుకోవడం అంచనా.",
        confidenceLow: "వైద్య పర్యవేక్షణ అవసరం కావచ్చు.",
        recoveryTimeline: "కోలుకోవడపు వేళాపట్టి",
        followUpRecommendations: "అనుసరణ సిఫార్సులు",
        mostPatientsRecover: "చాలా మంది రోగులు సరైన శ్రద్ధతో ఈ సమయంలో కోలుకుంటారు.",
        medicalDisclaimer: "వైద్య నిరాకరణ",
        disclaimerText: "ఇది విద్యా ప్రయోజనాల కోసం మాత్రమే AI-ఆధారిత మార్గదర్శక వ్యవస్థ. ఇది నిపుణుల వైద్య సలహాకు ప్రత్యామ్నాయం కాదు. అర్హత కలిగిన ఆరోగ్య సంరక్షణ ప్రదాతని ఎల్లప్పుడూ సంప్రదించండి.",
        downloadPDF: "PDF డౌన్‌లోడ్ చేయండి", emailReport: "ఇమెయిల్ నివేదిక", smsReminders: "SMS రిమైండర్లు",
        generating: "రూపొందిస్తోంది...", sending: "పంపిస్తోంది...",
        dur_less24h: "24 గంటల కంటే తక్కువ", dur_1_3d: "1-3 రోజులు", dur_3_7d: "3-7 రోజులు",
        dur_1_2w: "1-2 వారాలు", dur_more2w: "2 వారాల కంటే ఎక్కువ",
        sev_mild: "తేలికపాటి", sev_moderate: "మితమైన", sev_severe: "తీవ్రమైన",
        ex_fever: "జ్వరం, తలనొప్పి, ఒంటి నొప్పులు", ex_cough: "దగ్గు, గొంతు నొప్పి, నాసి కారడం",
        ex_stomach: "కడుపు నొప్పి, వికారం, వాంతులు", ex_chest: "ఛాతీ నొప్పి, శ్వాస ఇబ్బంది",
    },

    Hindi: {
        ...commonKeys,
        title: "IAP-MG GenAI का उपयोग करके",
        welcomeBack: "वापस स्वागत है", createAccount: "अपना खाता बनाएं",
        fullName: "पूरा नाम", email: "ईमेल", phone: "फोन नंबर", password: "पासवर्ड",
        register: "पंजीकरण करें", login: "लॉगिन", logout: "लॉगआउट",
        welcomeBackUser: "वापस स्वागत है, {name}",
        startNewDiagnosis: "नया निदान शुरू करें",
        totalSessions: "कुल सत्र", completed: "पूर्ण", language: "भाषा",
        recentSessions: "हाल के निदान सत्र",
        noSessions: "अभी तक कोई निदान सत्र नहीं",
        startFirst: "अपना पहला स्वास्थ्य मूल्यांकन शुरू करें",
        settings: "सेटिंग्स", changeLanguage: "भाषा बदलें",
        cancel: "रद्द करें", confirm: "पुष्टि करें", delete: "हटाएं", view: "देखें",
        readyToStart: "आज एक नया स्वास्थ्य मूल्यांकन शुरू करने के लिए तैयार हैं?",
        somethingWentWrong: "कुछ गलत हुआ", pending: "लंबित", emergency: "आपातकाल",
        aiMedicalDiagnosis: "AI चिकित्सा निदान",
        instantHealthAssessment: "Google Gemini AI द्वारा तत्काल स्वास्थ्य मूल्यांकन",
        symptoms: "लक्षण", aiAnalysis: "AI विश्लेषण",
        backToDashboard: "डैशबोर्ड पर जाएं",
        diagnosisResults: "निदान परिणाम",
        possibleConditions: "संभावित स्थितियां",
        tellUsWhatYouFeel: "बताइए आप कैसा महसूस कर रहे हैं",
        describeSymptomsDetail: "अपने लक्षणों का विस्तार से वर्णन करें। हमारा AI तुरंत मार्गदर्शन प्रदान करेगा।",
        describeSymptoms: "अपने लक्षण बताएं *",
        tipTitle: "सुझाव:", symptomTip: "जितना हो सके विशिष्ट रहें।",
        quickExamples: "त्वरित उदाहरण:", getAiDiagnosis: "AI निदान प्राप्त करें",
        analyzingSymptoms: "आपके लक्षणों का विश्लेषण हो रहा है...",
        analysisFailed: "विश्लेषण विफल", tryAgain: "पुनः प्रयास करें",
        yourAiDiagnosisResults: "आपके AI निदान परिणाम",
        analysisPoweredBy: "Google Gemini AI द्वारा विश्लेषण",
        mostLikely: "सबसे संभावित", confidence: "विश्वास",
        show: "दिखाएं", hide: "छुपाएं", clinicalReasoning: "नैदानिक तर्क",
        clickForBreakdown: "विवरण के लिए क्लिक करें",
        confidenceBreakdown: "विश्वास विभाजन",
        symptomMatch: "लक्षण मिलान", severityAlignment: "गंभीरता संरेखण",
        durationCorrelation: "अवधि सहसंबंध",
        symptomMatchDesc: "आपके लक्षण इस स्थिति से कितने मेल खाते हैं",
        severityAlignmentDesc: "लक्षण गंभीरता सामान्य प्रस्तुति से मेल खाती है",
        durationCorrelationDesc: "समयरेखा रोग प्रगति से मेल खाती है",
        clinicalReasoningDesc: "चिकित्सा पैटर्न का AI विश्लेषण",
        howWeCalculated: "हमने यह स्कोर कैसे गणना किया",
        overallScore: "समग्र विश्वास स्कोर", closeBreakdown: "बंद करें",
        weight: "भार", symptomRelief: "लक्षण राहत",
        scoreCalculationDesc: "AI ने 4 प्रमुख कारकों का विश्लेषण करके अंतिम स्कोर निकाला।",
        recommendedMedicines: "💊 अनुशंसित दवाएं",
        medicinesSubtitle: "लक्षण राहत के लिए OTC दवाएं (केवल जानकारी के लिए)",
        medicineDosage: "खुराक", medicineFrequency: "आवृत्ति",
        medicineDuration: "अवधि", medicineTiming: "समय",
        medicineSideEffects: "दुष्प्रभाव", medicineNo: "दवा",
        otcWarning: "⚠️ महत्वपूर्ण: ये सामान्य OTC दवाओं के सुझाव हैं। कोई भी दवा लेने से पहले फार्मासिस्ट या डॉक्टर से परामर्श करें, विशेषकर यदि आपको पहले से कोई बीमारी या एलर्जी है।",
        dietRecommendations: "🥗 आहार सिफारिशें",
        dietSubtitle: "ठीक होने में मदद करने वाले और बचने वाले खाद्य पदार्थ",
        foodsToEat: "खाने के लिए खाद्य पदार्थ", foodsToAvoid: "बचने वाले खाद्य पदार्थ",
        noSpecificRecommendations: "कोई विशिष्ट सिफारिश नहीं",
        noSpecificRestrictions: "कोई विशिष्ट प्रतिबंध नहीं",
        dietTip: "💡 सुझाव: पर्याप्त तरल पदार्थों के साथ संतुलित आहार बनाए रखें। एलर्जी के आधार पर व्यक्तिगत जरूरतें अलग हो सकती हैं।",
        safetyPrecautions: "🛡️ सुरक्षा सावधानियां",
        precautionsSubtitle: "तेजी से ठीक होने के लिए महत्वपूर्ण उपाय",
        seekMedicalAttention: "⚠️ तत्काल चिकित्सा सहायता कब लें:",
        warnSymptomsWorsen: "लक्षण काफी बिगड़ जाएं",
        warnHighFever: "3 दिन से अधिक तेज बुखार रहे",
        warnBreathing: "सांस लेने में कठिनाई या सीने में दर्द हो",
        warnDehydration: "गंभीर निर्जलीकरण या तरल पदार्थ न ले पाना",
        warnSuddenChange: "स्थिति में कोई अचानक या चिंताजनक परिवर्तन",
        recoveryInformation: "⏱️ ठीक होने की जानकारी",
        recoverySubtitle: "अनुमानित समयरेखा और अनुवर्ती मार्गदर्शन",
        expectedRecovery: "अनुमानित ठीक होना", recoveryOutlook: "ठीक होने की संभावना",
        confidenceHigh: "अनुशंसित उपचार के साथ पूरी तरह ठीक होने की उम्मीद है।",
        confidenceMedium: "उचित देखभाल के साथ अच्छे ठीक होने की उम्मीद।",
        confidenceLow: "ठीक होने के लिए चिकित्सा पर्यवेक्षण की जरूरत हो सकती है।",
        recoveryTimeline: "ठीक होने की समयरेखा",
        followUpRecommendations: "अनुवर्ती सिफारिशें",
        mostPatientsRecover: "अधिकांश रोगी उचित देखभाल के साथ इस समय सीमा में ठीक हो जाते हैं।",
        medicalDisclaimer: "चिकित्सा अस्वीकरण",
        disclaimerText: "यह केवल शैक्षिक उद्देश्यों के लिए AI-संचालित मार्गदर्शन प्रणाली है। यह पेशेवर चिकित्सा सलाह का विकल्प नहीं है। हमेशा योग्य स्वास्थ्य सेवा प्रदाता से परामर्श करें।",
        downloadPDF: "PDF डाउनलोड करें", emailReport: "ईमेल रिपोर्ट", smsReminders: "SMS रिमाइंडर",
        generating: "बन रहा है...", sending: "भेजा जा रहा है...",
        dur_less24h: "24 घंटे से कम", dur_1_3d: "1-3 दिन", dur_3_7d: "3-7 दिन",
        dur_1_2w: "1-2 सप्ताह", dur_more2w: "2 सप्ताह से अधिक",
        sev_mild: "हल्का", sev_moderate: "मध्यम", sev_severe: "गंभीर",
        ex_fever: "बुखार, सिरदर्द, शरीर दर्द", ex_cough: "खांसी, गले में दर्द, नाक बहना",
        ex_stomach: "पेट दर्द, मतली, उल्टी", ex_chest: "सीने में दर्द, सांस लेने में कठिनाई",
    },

    Tamil: {
        ...commonKeys,
        title: "IAP-MG GenAI பயன்படுத்தி",
        welcomeBack: "மீண்டும் வரவேற்கிறோம்", login: "உள்நுழை", logout: "வெளியேறு",
        welcomeBackUser: "மீண்டும் வரவேற்கிறோம், {name}",
        startNewDiagnosis: "புதிய நோய் கண்டறிதல் தொடங்கு",
        settings: "அமைப்புகள்", changeLanguage: "மொழி மாற்றவும்",
        cancel: "ரத்து செய்", confirm: "உறுதிப்படுத்து", delete: "நீக்கு",
        readyToStart: "இன்று புதிய சுகாதார மதிப்பீடு தொடங்க தயாரா?",
        aiMedicalDiagnosis: "AI மருத்துவ நோய் கண்டறிதல்",
        symptoms: "அறிகுறிகள்", aiAnalysis: "AI பகுப்பாய்வு",
        backToDashboard: "டாஷ்போர்டுக்கு செல்லுங்கள்",
        possibleConditions: "சாத்தியமான நிலைமைகள்",
        tellUsWhatYouFeel: "நீங்கள் எப்படி உணர்கிறீர்கள் என்று சொல்லுங்கள்",
        describeSymptoms: "உங்கள் அறிகுறிகளை விவரிக்கவும் *",
        tipTitle: "குறிப்பு:", symptomTip: "முடிந்தவரை குறிப்பிட்டு சொல்லுங்கள்.",
        getAiDiagnosis: "AI நோய் கண்டறிதல் பெறுங்கள்",
        analyzingSymptoms: "உங்கள் அறிகுறிகள் பகுப்பாய்வு செய்யப்படுகின்றன...",
        mostLikely: "மிகவும் சாத்தியம்", confidence: "நம்பகத்தன்மை",
        show: "காட்டு", hide: "மறை", clinicalReasoning: "மருத்துவ தர்க்கம்",
        clickForBreakdown: "விவரங்களுக்கு கிளிக் செய்யுங்கள்",
        confidenceBreakdown: "நம்பகத்தன்மை விவரம்",
        symptomMatch: "அறிகுறி பொருத்தம்", severityAlignment: "தீவிரம் சீரமைப்பு",
        durationCorrelation: "கால அளவு தொடர்பு",
        symptomMatchDesc: "உங்கள் அறிகுறிகள் இந்த நிலையுடன் எவ்வளவு பொருந்துகின்றன",
        severityAlignmentDesc: "அறிகுறி தீவிரம் வழக்கமான வழக்குரையுடன் பொருந்துகிறது",
        durationCorrelationDesc: "காலவரிசை நோய் முன்னேற்றத்துடன் பொருந்துகிறது",
        clinicalReasoningDesc: "மருத்துவ முறைகளின் AI பகுப்பாய்வு",
        howWeCalculated: "இந்த மதிப்பெண்ணை எவ்வாறு கணக்கிட்டோம்",
        overallScore: "ஒட்டுமொத்த நம்பகத்தன்மை மதிப்பெண்", closeBreakdown: "மூடு",
        weight: "எடை", scoreCalculationDesc: "AI 4 முக்கிய காரணிகளை பகுப்பாய்வு செய்து மதிப்பெண் கணக்கிட்டது.",
        recommendedMedicines: "💊 பரிந்துரைக்கப்பட்ட மருந்துகள்",
        medicinesSubtitle: "அறிகுறி நிவாரணத்திற்கான OTC மருந்துகள் (தகவல் நோக்கம் மட்டும்)",
        medicineDosage: "அளவு", medicineFrequency: "அதிர்வெண்",
        medicineDuration: "காலம்", medicineTiming: "நேரம்",
        medicineSideEffects: "பக்க விளைவுகள்", medicineNo: "மருந்து",
        otcWarning: "⚠️ முக்கியம்: இவை பொதுவான OTC மருந்து பரிந்துரைகள். எந்த மருந்தும் எடுக்கும் முன் மருத்துவரிடம் ஆலோசிக்கவும்.",
        dietRecommendations: "🥗 உணவு பரிந்துரைகள்",
        dietSubtitle: "குணமடைய உதவும் மற்றும் தவிர்க்க வேண்டிய உணவுகள்",
        foodsToEat: "சாப்பிட வேண்டிய உணவுகள்", foodsToAvoid: "தவிர்க்க வேண்டிய உணவுகள்",
        noSpecificRecommendations: "குறிப்பிட்ட பரிந்துரைகள் இல்லை",
        noSpecificRestrictions: "குறிப்பிட்ட கட்டுப்பாடுகள் இல்லை",
        dietTip: "💡 குறிப்பு: நிறைய திரவங்களுடன் சமச்சீர் உணவை பராமரிக்கவும்.",
        safetyPrecautions: "🛡️ பாதுகாப்பு முன்னெச்சரிக்கைகள்",
        precautionsSubtitle: "விரைவாக குணமடைய கடைப்பிடிக்க வேண்டிய நடவடிக்கைகள்",
        seekMedicalAttention: "⚠️ உடனடி மருத்துவ கவனிப்பு எப்போது தேடுவது:",
        warnSymptomsWorsen: "அறிகுறிகள் கணிசமாக மோசமடைகின்றன",
        warnHighFever: "3 நாட்களுக்கு மேல் அதிக காய்ச்சல் நீடிக்கிறது",
        warnBreathing: "சுவாசிக்க சிரமம் அல்லது மார்பு வலி",
        warnDehydration: "கடுமையான நீர்ச்சத்து குறைபாடு",
        warnSuddenChange: "நிலையில் திடீர் அல்லது கவலைப்படும் மாற்றங்கள்",
        recoveryInformation: "⏱️ குணமடைவு தகவல்",
        recoverySubtitle: "எதிர்பார்க்கப்படும் காலக்கெடு மற்றும் பின்தொடர்தல்",
        expectedRecovery: "எதிர்பார்க்கப்படும் குணமடைவு", recoveryOutlook: "குணமடைவு வாய்ப்பு",
        confidenceHigh: "பரிந்துரைக்கப்பட்ட சிகிச்சையுடன் முழு குணமடைவு எதிர்பார்க்கப்படுகிறது.",
        confidenceMedium: "சரியான கவனிப்புடன் நல்ல குணமடைவு எதிர்பார்க்கப்படுகிறது.",
        confidenceLow: "குணமடைவுக்கு மருத்துவ கண்காணிப்பு தேவைப்படலாம்.",
        recoveryTimeline: "குணமடைவு காலக்கெடு",
        followUpRecommendations: "பின்தொடர்தல் பரிந்துரைகள்",
        mostPatientsRecover: "பெரும்பாலான நோயாளிகள் சரியான கவனிப்புடன் குணமடைகிறார்கள்.",
        medicalDisclaimer: "மருத்துவ மறுப்பு",
        disclaimerText: "இது கல்வி நோக்கங்களுக்காக மட்டுமே AI-இயக்கப்படும் வழிகாட்டுதல். இது தொழில்முறை மருத்துவ ஆலோசனைக்கு மாற்றாக இல்லை.",
        downloadPDF: "PDF பதிவிறக்கவும்", emailReport: "மின்னஞ்சல் அறிக்கை",
        sev_mild: "லேசான", sev_moderate: "மிதமான", sev_severe: "கடுமையான",
        ex_fever: "காய்ச்சல், தலைவலி, உடல் வலி", ex_cough: "இருமல், தொண்டை வலி",
        ex_stomach: "வயிற்று வலி, குமட்டல்", ex_chest: "மார்பு வலி, சுவாசிக்க சிரமம்",
    },

    Kannada: {
        ...commonKeys,
        title: "IAP-MG GenAI ಬಳಸಿ",
        welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ", login: "ಲಾಗಿನ್", logout: "ಲಾಗ್ ಔಟ್",
        welcomeBackUser: "ಮತ್ತೆ ಸ್ವಾಗತ, {name}",
        startNewDiagnosis: "ಹೊಸ ರೋಗನಿರ್ಣಯ ಪ್ರಾರಂಭಿಸಿ",
        settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", changeLanguage: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
        cancel: "ರದ್ದು ಮಾಡಿ", confirm: "ದೃಢೀಕರಿಸಿ",
        aiMedicalDiagnosis: "AI ವೈದ್ಯಕೀಯ ರೋಗನಿರ್ಣಯ",
        possibleConditions: "ಸಾಧ್ಯವಾದ ಪರಿಸ್ಥಿತಿಗಳು",
        tellUsWhatYouFeel: "ನೀವು ಹೇಗೆ ಅನುಭವಿಸುತ್ತಿದ್ದೀರಿ ಎಂದು ಹೇಳಿ",
        getAiDiagnosis: "AI ರೋಗನಿರ್ಣಯ ಪಡೆಯಿರಿ",
        mostLikely: "ಹೆಚ್ಚು ಸಾಧ್ಯ", confidence: "ವಿಶ್ವಾಸ",
        show: "ತೋರಿಸಿ", hide: "ಮರೆಮಾಡಿ", clinicalReasoning: "ಕ್ಲಿನಿಕಲ್ ತರ್ಕ",
        clickForBreakdown: "ವಿವರಗಳಿಗೆ ಕ್ಲಿಕ್ ಮಾಡಿ",
        confidenceBreakdown: "ವಿಶ್ವಾಸ ವಿವರ",
        symptomMatch: "ರೋಗಲಕ್ಷಣ ಹೊಂದಾಣಿಕೆ", severityAlignment: "ತೀವ್ರತೆ ಜೋಡಣೆ",
        durationCorrelation: "ಅವಧಿ ಪರಸ್ಪರ ಸಂಬಂಧ",
        howWeCalculated: "ಈ ಸ್ಕೋರ್ ಹೇಗೆ ಲೆಕ್ಕ ಹಾಕಿದ್ದೇವೆ",
        overallScore: "ಒಟ್ಟಾರೆ ವಿಶ್ವಾಸ ಸ್ಕೋರ್", closeBreakdown: "ಮುಚ್ಚಿ",
        weight: "ತೂಕ", scoreCalculationDesc: "AI 4 ಪ್ರಮುಖ ಅಂಶಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ ಅಂತಿಮ ಸ್ಕೋರ್ ಲೆಕ್ಕ ಹಾಕಿದೆ.",
        recommendedMedicines: "💊 ಶಿಫಾರಸು ಮಾಡಿದ ಔಷಧಗಳು",
        medicinesSubtitle: "ರೋಗಲಕ್ಷಣ ನಿವಾರಣೆಗಾಗಿ OTC ಔಷಧಗಳು (ಮಾಹಿತಿ ಉದ್ದೇಶಕ್ಕಾಗಿ ಮಾತ್ರ)",
        medicineDosage: "ಪ್ರಮಾಣ", medicineFrequency: "ಆವರ್ತನ",
        medicineDuration: "ಅವಧಿ", medicineTiming: "ಸಮಯ",
        medicineSideEffects: "ಅಡ್ಡ ಪರಿಣಾಮಗಳು", medicineNo: "ಔಷಧ",
        otcWarning: "⚠️ ಮುಖ್ಯ: ಇವು ಸಾಮಾನ್ಯ OTC ಔಷಧ ಸಲಹೆಗಳು. ಯಾವುದೇ ಔಷಧ ತೆಗೆದುಕೊಳ್ಳುವ ಮೊದಲು ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
        dietRecommendations: "🥗 ಆಹಾರ ಶಿಫಾರಸುಗಳು",
        dietSubtitle: "ಚೇತರಿಕೆಗೆ ಸಹಾಯ ಮಾಡುವ ಮತ್ತು ತಪ್ಪಿಸಬೇಕಾದ ಆಹಾರಗಳು",
        foodsToEat: "ತಿನ್ನಬೇಕಾದ ಆಹಾರಗಳು", foodsToAvoid: "ತಪ್ಪಿಸಬೇಕಾದ ಆಹಾರಗಳು",
        noSpecificRecommendations: "ನಿರ್ದಿಷ್ಟ ಶಿಫಾರಸುಗಳಿಲ್ಲ",
        noSpecificRestrictions: "ನಿರ್ದಿಷ್ಟ ನಿರ್ಬಂಧಗಳಿಲ್ಲ",
        dietTip: "💡 ಸಲಹೆ: ಸಾಕಷ್ಟು ದ್ರವಪದಾರ್ಥಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರ ಕಾಪಾಡಿಕೊಳ್ಳಿ.",
        safetyPrecautions: "🛡️ ಸುರಕ್ಷತಾ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು",
        precautionsSubtitle: "ವೇಗವಾಗಿ ಚೇತರಿಸಲು ಅನುಸರಿಸಬೇಕಾದ ಕ್ರಮಗಳು",
        seekMedicalAttention: "⚠️ ತಕ್ಷಣ ವೈದ್ಯಕೀಯ ಸಹಾಯ ಯಾವಾಗ ಪಡೆಯಬೇಕು:",
        warnSymptomsWorsen: "ರೋಗಲಕ್ಷಣಗಳು ಗಮನಾರ್ಹವಾಗಿ ಹದಗೆಡುತ್ತವೆ",
        warnHighFever: "3 ದಿನಗಳಿಗಿಂತ ಹೆಚ್ಚು ಅಧಿಕ ಜ್ವರ",
        warnBreathing: "ಉಸಿರಾಟದ ತೊಂದರೆ ಅಥವಾ ಎದೆ ನೋವು",
        warnDehydration: "ತೀವ್ರ ನಿರ್ಜಲೀಕರಣ", warnSuddenChange: "ಸ್ಥಿತಿಯಲ್ಲಿ ಯಾವುದೇ ಹಠಾತ್ ಬದಲಾವಣೆ",
        recoveryInformation: "⏱️ ಚೇತರಿಕೆ ಮಾಹಿತಿ",
        recoverySubtitle: "ನಿರೀಕ್ಷಿತ ಕಾಲರೇಖೆ ಮತ್ತು ಅನುಸರಣ ಮಾರ್ಗದರ್ಶನ",
        expectedRecovery: "ನಿರೀಕ್ಷಿತ ಚೇತರಿಕೆ", recoveryOutlook: "ಚೇತರಿಕೆ ನಿರೀಕ್ಷೆ",
        confidenceHigh: "ಶಿಫಾರಸು ಚಿಕಿತ್ಸೆಯೊಂದಿಗೆ ಸಂಪೂರ್ಣ ಚೇತರಿಕೆ ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ.",
        confidenceMedium: "ಸರಿಯಾದ ಆರೈಕೆಯೊಂದಿಗೆ ಉತ್ತಮ ಚೇತರಿಕೆ ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ.",
        confidenceLow: "ಚೇತರಿಕೆಗೆ ವೈದ್ಯಕೀಯ ಮೇಲ್ವಿಚಾರಣೆ ಅಗತ್ಯವಾಗಬಹುದು.",
        recoveryTimeline: "ಚೇತರಿಕೆ ವೇಳಾಪಟ್ಟಿ",
        followUpRecommendations: "ಅನುಸರಣ ಶಿಫಾರಸುಗಳು",
        mostPatientsRecover: "ಹೆಚ್ಚಿನ ರೋಗಿಗಳು ಸರಿಯಾದ ಆರೈಕೆಯೊಂದಿಗೆ ಚೇತರಿಸುತ್ತಾರೆ.",
        medicalDisclaimer: "ವೈದ್ಯಕೀಯ ಹಕ್ಕು ನಿರಾಕರಣೆ",
        disclaimerText: "ಇದು ಶೈಕ್ಷಣಿಕ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ AI-ಚಾಲಿತ ಮಾರ್ಗದರ್ಶನ ವ್ಯವಸ್ಥೆ. ಇದು ವೃತ್ತಿಪರ ವೈದ್ಯಕೀಯ ಸಲಹೆಗೆ ಬದಲಿಯಲ್ಲ.",
        ex_fever: "ಜ್ವರ, ತಲೆನೋವು, ದೇಹ ನೋವು", ex_cough: "ಕೆಮ್ಮು, ಗಂಟಲು ನೋವು",
    },

    Malayalam: {
        ...commonKeys,
        title: "IAP-MG GenAI ഉപയോഗിച്ച്",
        welcomeBack: "തിരിച്ചു സ്വാഗതം", login: "ലോഗിൻ", logout: "ലോഗൗട്ട്",
        welcomeBackUser: "തിരിച്ചു സ്വാഗതം, {name}",
        startNewDiagnosis: "പുതിയ രോഗനിർണ്ണയം ആരംഭിക്കുക",
        settings: "ക്രമീകരണങ്ങൾ", changeLanguage: "ഭാഷ മാറ്റുക",
        cancel: "റദ്ദാക്കുക", confirm: "സ്ഥിരീകരിക്കുക",
        aiMedicalDiagnosis: "AI വൈദ്യ രോഗനിർണ്ണയം",
        possibleConditions: "സാദ്ധ്യമായ അവസ്ഥകൾ",
        getAiDiagnosis: "AI രോഗനിർണ്ണയം നേടുക",
        mostLikely: "ഏറ്റവും സാദ്ധ്യത", confidence: "ആത്മവിശ്വാസം",
        show: "കാണിക്കുക", hide: "മറയ്ക്കുക", clinicalReasoning: "ക്ലിനിക്കൽ യുക്തി",
        clickForBreakdown: "വിശദാംശങ്ങൾക്ക് ക്ലിക്ക് ചെയ്യുക",
        confidenceBreakdown: "ആത്മവിശ്വാസ വിവരം",
        howWeCalculated: "ഈ സ്കോർ എങ്ങനെ കണക്കാക്കി",
        overallScore: "മൊത്തം ആത്മവിശ്വാസ സ്കോർ", closeBreakdown: "അടയ്ക്കുക",
        weight: "ഭാരം", scoreCalculationDesc: "AI 4 പ്രധാന ഘടകങ്ങൾ വിശകലനം ചെയ്ത് അന്തിമ സ്കോർ കണക്കാക്കി.",
        recommendedMedicines: "💊 ശുപാർശ ചെയ്ത മരുന്നുകൾ",
        medicinesSubtitle: "രോഗലക്ഷണ ആശ്വാസത്തിനുള്ള OTC മരുന്നുകൾ (വിവര ആവശ്യത്തിന് മാത്രം)",
        medicineDosage: "ഡോസ്", medicineFrequency: "ആവൃത്തി",
        medicineDuration: "കാലാവധി", medicineTiming: "സമയം",
        medicineSideEffects: "പ്രതികൂല ഫലങ്ങൾ", medicineNo: "മരുന്ന്",
        otcWarning: "⚠️ പ്രധാനം: ഇവ പൊതുവായ OTC മരുന്ന് നിർദ്ദേശങ്ങളാണ്. ഏതെങ്കിലും മരുന്ന് കഴിക്കുന്നതിന് മുൻപ് ഡോക്ടറുമായി ആലോചിക്കുക.",
        dietRecommendations: "🥗 ഭക്ഷണ ശുപാർശകൾ",
        dietSubtitle: "ആരോഗ്യ സൗഖ്യത്തിന് സഹായിക്കുന്നതും ഒഴിവാക്കേണ്ടതുമായ ഭക്ഷണങ്ങൾ",
        foodsToEat: "കഴിക്കേണ്ട ഭക്ഷണങ്ങൾ", foodsToAvoid: "ഒഴിവാക്കേണ്ട ഭക്ഷണങ്ങൾ",
        noSpecificRecommendations: "പ്രത്യേക ശുപാർശകളൊന്നുമില്ല",
        noSpecificRestrictions: "പ്രത്യേക നിയന്ത്രണങ്ങളൊന്നുമില്ല",
        dietTip: "💡 നുറുങ്ങ്: ധാരാളം ദ്രാവകങ്ങളോടൊപ്പം സമതുലിത ഭക്ഷണം കഴിക്കുക.",
        safetyPrecautions: "🛡️ സുരക്ഷാ മുൻകരുതലുകൾ",
        precautionsSubtitle: "വേഗത്തിൽ ആരോഗ്യം വീണ്ടെടുക്കാൻ പാലിക്കേണ്ട നടപടികൾ",
        seekMedicalAttention: "⚠️ ഉടനടി വൈദ്യ സഹായം എപ്പോൾ നേടണം:",
        warnSymptomsWorsen: "രോഗലക്ഷണങ്ങൾ ഗണ്യമായി വഷളാകുന്നു",
        warnHighFever: "3 ദിവസത്തിൽ കൂടുതൽ ഉയർന്ന പനി",
        warnBreathing: "ശ്വസനം ബുദ്ധിമുട്ടോ നെഞ്ചുവേദനയോ",
        warnDehydration: "കഠിനമായ നിർജ്ജലീകരണം",
        warnSuddenChange: "അവസ്ഥയിൽ ഏതെങ്കിലും പെട്ടെന്നുള്ള മാറ്റം",
        recoveryInformation: "⏱️ സൗഖ്യലാഭ വിവരം",
        recoverySubtitle: "പ്രതീക്ഷിത കാലക്രമം ഉം ഫോളോ-അപ്പ് മാർഗ്ഗനിർദ്ദേശവും",
        expectedRecovery: "പ്രതീക്ഷിത സൗഖ്യലാഭം", recoveryOutlook: "സൗഖ്യലാഭ സാദ്ധ്യത",
        confidenceHigh: "ശുപാർശ ചെയ്ത ചികിത്സയോടൊപ്പം പൂർണ്ണ സൗഖ്യലാഭം പ്രതീക്ഷിക്കുന്നു.",
        confidenceMedium: "ശരിയായ പരിചരണത്തോടൊപ്പം നല്ല സൗഖ്യലാഭം.",
        confidenceLow: "സൗഖ്യലാഭത്തിന് വൈദ്യ മേൽനോട്ടം ആവശ്യമാകാം.",
        recoveryTimeline: "സൗഖ്യലാഭ കാലക്രമം",
        followUpRecommendations: "ഫോളോ-അപ്പ് ശുപാർശകൾ",
        mostPatientsRecover: "മിക്ക രോഗികളും ശരിയായ പരിചരണത്തോടൊപ്പം ഈ കാലയളവിൽ സൗഖ്യം പ്രാപിക്കുന്നു.",
        medicalDisclaimer: "വൈദ്യ നിരാകരണം",
        disclaimerText: "ഇത് വിദ്യാഭ്യാസ ആവശ്യങ്ങൾക്ക് മാത്രം AI-പ്രവർത്തിത മാർഗ്ഗനിർദ്ദേശ സംവിധാനമാണ്. ഇത് പ്രൊഫഷണൽ വൈദ്യ ഉപദേശത്തിന് പകരമല്ല.",
        ex_fever: "പനി, തലവേദന, ശരീരവേദന", ex_cough: "ചുമ, തൊണ്ടവേദന",
    },

    Marathi: {
        ...commonKeys,
        title: "IAP-MG GenAI वापरून",
        welcomeBack: "परत स्वागत आहे", login: "लॉगिन", logout: "लॉगआउट",
        welcomeBackUser: "परत स्वागत आहे, {name}",
        startNewDiagnosis: "नवीन निदान सुरू करा",
        settings: "सेटिंग्ज", changeLanguage: "भाषा बदला",
        cancel: "रद्द करा", confirm: "पुष्टी करा",
        aiMedicalDiagnosis: "AI वैद्यकीय निदान",
        possibleConditions: "संभाव्य परिस्थिती",
        getAiDiagnosis: "AI निदान मिळवा",
        mostLikely: "सर्वात शक्यता", confidence: "विश्वास",
        show: "दाखवा", hide: "लपवा", clinicalReasoning: "नैदानिक तर्क",
        clickForBreakdown: "तपशीलांसाठी क्लिक करा",
        confidenceBreakdown: "विश्वास तपशील",
        howWeCalculated: "हा स्कोर कसा मोजला", overallScore: "एकूण विश्वास स्कोर",
        closeBreakdown: "बंद करा", weight: "वजन",
        scoreCalculationDesc: "AI ने 4 महत्त्वाच्या घटकांचे विश्लेषण करून अंतिम स्कोर मोजला.",
        recommendedMedicines: "💊 शिफारस केलेली औषधे",
        medicinesSubtitle: "लक्षण आराम करण्यासाठी OTC औषधे (केवळ माहितीसाठी)",
        medicineDosage: "मात्रा", medicineFrequency: "वारंवारता",
        medicineDuration: "कालावधी", medicineTiming: "वेळ",
        medicineSideEffects: "दुष्परिणाम", medicineNo: "औषध",
        otcWarning: "⚠️ महत्त्वाचे: ही सामान्य OTC औषधांच्या सूचना आहेत. कोणतेही औषध घेण्यापूर्वी डॉक्टरांशी सल्लामसलत करा.",
        dietRecommendations: "🥗 आहार शिफारसी",
        dietSubtitle: "बरे होण्यास मदत करणारे आणि टाळायचे पदार्थ",
        foodsToEat: "खायचे पदार्थ", foodsToAvoid: "टाळायचे पदार्थ",
        noSpecificRecommendations: "कोणत्याही विशिष्ट शिफारसी नाहीत",
        noSpecificRestrictions: "कोणत्याही विशिष्ट निर्बंध नाहीत",
        dietTip: "💡 सल्ला: भरपूर द्रव पदार्थांसह संतुलित आहार घ्या.",
        safetyPrecautions: "🛡️ सुरक्षा खबरदारी",
        precautionsSubtitle: "जलद बरे होण्यासाठी अनुसरण करावयाचे उपाय",
        seekMedicalAttention: "⚠️ त्वरित वैद्यकीय मदत कधी घ्यावी:",
        warnSymptomsWorsen: "लक्षणे लक्षणीयरित्या बिघडतात",
        warnHighFever: "3 दिवसांपेक्षा जास्त उच्च ताप",
        warnBreathing: "श्वास घेण्यात अडचण किंवा छातीत दुखणे",
        warnDehydration: "तीव्र निर्जलीकरण", warnSuddenChange: "परिस्थितीत कोणताही अचानक बदल",
        recoveryInformation: "⏱️ बरे होण्याची माहिती",
        recoverySubtitle: "अपेक्षित वेळापत्रक आणि पाठपुरावा मार्गदर्शन",
        expectedRecovery: "अपेक्षित बरे होणे", recoveryOutlook: "बरे होण्याची शक्यता",
        confidenceHigh: "शिफारस केलेल्या उपचाराने पूर्ण बरे होण्याची अपेक्षा आहे.",
        confidenceMedium: "योग्य काळजीने चांगले बरे होण्याची अपेक्षा.",
        confidenceLow: "बरे होण्यासाठी वैद्यकीय देखरेख आवश्यक असू शकते.",
        recoveryTimeline: "बरे होण्याचे वेळापत्रक",
        followUpRecommendations: "पाठपुरावा शिफारसी",
        mostPatientsRecover: "बहुतांश रुग्ण योग्य काळजीने या कालावधीत बरे होतात.",
        medicalDisclaimer: "वैद्यकीय अस्वीकरण",
        disclaimerText: "हे केवळ शैक्षणिक उद्देशांसाठी AI-चालित मार्गदर्शन प्रणाली आहे. हे व्यावसायिक वैद्यकीय सल्ल्याचा पर्याय नाही.",
        ex_fever: "ताप, डोकेदुखी, अंगदुखी", ex_cough: "खोकला, घसादुखी",
    },

    Bengali: {
        ...commonKeys,
        title: "IAP-MG GenAI ব্যবহার করে",
        welcomeBack: "ফিরে আসতে স্বাগতম", login: "লগইন", logout: "লগআউট",
        welcomeBackUser: "ফিরে আসতে স্বাগতম, {name}",
        startNewDiagnosis: "নতুন রোগ নির্ণয় শুরু করুন",
        settings: "সেটিংস", changeLanguage: "ভাষা পরিবর্তন করুন",
        cancel: "বাতিল করুন", confirm: "নিশ্চিত করুন",
        aiMedicalDiagnosis: "AI চিকিৎসা রোগ নির্ণয়",
        possibleConditions: "সম্ভাব্য অবস্থা",
        getAiDiagnosis: "AI রোগ নির্ণয় পান",
        mostLikely: "সবচেয়ে সম্ভাব্য", confidence: "আস্থা",
        show: "দেখান", hide: "লুকান", clinicalReasoning: "ক্লিনিকাল যুক্তি",
        clickForBreakdown: "বিস্তারিত জানতে ক্লিক করুন",
        confidenceBreakdown: "আস্থা বিস্তারিত",
        howWeCalculated: "এই স্কোর কীভাবে গণনা করা হয়েছে",
        overallScore: "সামগ্রিক আস্থা স্কোর", closeBreakdown: "বন্ধ করুন",
        weight: "ওজন", scoreCalculationDesc: "AI 4টি মূল কারণ বিশ্লেষণ করে চূড়ান্ত স্কোর গণনা করেছে।",
        recommendedMedicines: "💊 প্রস্তাবিত ওষুধ",
        medicinesSubtitle: "লক্ষণ উপশমের জন্য OTC ওষুধ (শুধুমাত্র তথ্যের উদ্দেশ্যে)",
        medicineDosage: "মাত্রা", medicineFrequency: "ফ্রিকোয়েন্সি",
        medicineDuration: "সময়কাল", medicineTiming: "সময়",
        medicineSideEffects: "পার্শ্ব প্রতিক্রিয়া", medicineNo: "ওষুধ",
        otcWarning: "⚠️ গুরুত্বপূর্ণ: এগুলো সাধারণ OTC ওষুধের পরামর্শ। যেকোনো ওষুধ খাওয়ার আগে ডাক্তারের সাথে পরামর্শ করুন।",
        dietRecommendations: "🥗 খাদ্য পরামর্শ",
        dietSubtitle: "সুস্থ হতে সাহায্যকারী এবং এড়ানো উচিত খাবার",
        foodsToEat: "খাওয়ার উচিত খাবার", foodsToAvoid: "এড়ানো উচিত খাবার",
        noSpecificRecommendations: "কোনো নির্দিষ্ট পরামর্শ নেই",
        noSpecificRestrictions: "কোনো নির্দিষ্ট বিধিনিষেধ নেই",
        dietTip: "💡 পরামর্শ: প্রচুর তরলের সাথে সুষম খাদ্য বজায় রাখুন।",
        safetyPrecautions: "🛡️ নিরাপত্তা সতর্কতা",
        precautionsSubtitle: "দ্রুত সুস্থ হওয়ার জন্য অনুসরণ করার গুরুত্বপূর্ণ ব্যবস্থা",
        seekMedicalAttention: "⚠️ কখন তাৎক্ষণিক চিকিৎসা সহায়তা নেবেন:",
        warnSymptomsWorsen: "লক্ষণগুলি উল্লেখযোগ্যভাবে খারাপ হয়",
        warnHighFever: "৩ দিনের বেশি উচ্চ জ্বর থাকে",
        warnBreathing: "শ্বাস নিতে অসুবিধা বা বুকে ব্যথা",
        warnDehydration: "গুরুতর পানিশূন্যতা", warnSuddenChange: "অবস্থায় যেকোনো হঠাৎ পরিবর্তন",
        recoveryInformation: "⏱️ সুস্থতার তথ্য",
        recoverySubtitle: "প্রত্যাশিত সময়রেখা এবং ফলো-আপ গাইডেন্স",
        expectedRecovery: "প্রত্যাশিত সুস্থতা", recoveryOutlook: "সুস্থতার সম্ভাবনা",
        confidenceHigh: "প্রস্তাবিত চিকিৎসায় পূর্ণ সুস্থতা প্রত্যাশিত।",
        confidenceMedium: "সঠিক যত্নে ভালো সুস্থতা প্রত্যাশিত।",
        confidenceLow: "সুস্থতার জন্য চিকিৎসা তত্ত্বাবধান প্রয়োজন হতে পারে।",
        recoveryTimeline: "সুস্থতার সময়রেখা",
        followUpRecommendations: "ফলো-আপ পরামর্শ",
        mostPatientsRecover: "বেশিরভাগ রোগী সঠিক যত্নে এই সময়সীমার মধ্যে সুস্থ হয়।",
        medicalDisclaimer: "চিকিৎসা দায়িত্বমুক্তি",
        disclaimerText: "এটি শুধুমাত্র শিক্ষামূলক উদ্দেশ্যে AI-চালিত গাইডেন্স সিস্টেম। এটি পেশাদার চিকিৎসা পরামর্শের বিকল্প নয়।",
        ex_fever: "জ্বর, মাথাব্যথা, শরীর ব্যথা", ex_cough: "কাশি, গলা ব্যথা",
    },

    Gujarati: {
        ...commonKeys,
        title: "IAP-MG GenAI ઉપયોગ કરીને",
        welcomeBack: "પાછા સ્વાગત છે", login: "લૉગિન", logout: "લૉગઆઉટ",
        welcomeBackUser: "પાછા સ્વાગત છે, {name}",
        startNewDiagnosis: "નવી નિદાન શરૂ કરો",
        settings: "સેટિંગ્સ", changeLanguage: "ભાષા બદલો",
        cancel: "રદ્દ કરો", confirm: "પુષ્ટિ કરો",
        aiMedicalDiagnosis: "AI તબીબી નિદાન",
        possibleConditions: "સંભવિત સ્થિતિઓ",
        getAiDiagnosis: "AI નિદાન મેળવો",
        mostLikely: "સૌથી સંભવ", confidence: "વિશ્વાસ",
        show: "બતાવો", hide: "છુપાવો", clinicalReasoning: "ક્લિનિકલ તર્ક",
        clickForBreakdown: "વિગતો માટે ક્લિક કરો",
        confidenceBreakdown: "વિશ્વાસ વિગત",
        howWeCalculated: "આ સ્કોર કેવી રીતે ગણ્યો", overallScore: "કુલ વિશ્વાસ સ્કોર",
        closeBreakdown: "બંધ કરો", weight: "વજન",
        scoreCalculationDesc: "AI એ 4 મુખ્ય પરિબળોનું વિશ્લેષણ કરી અંતિમ સ્કોર ગણ્યો.",
        recommendedMedicines: "💊 ભલામણ કરેલી દવાઓ",
        medicinesSubtitle: "લક્ષણ રાહત માટે OTC દવાઓ (ફક્ત માહિતી માટે)",
        medicineDosage: "માત્રા", medicineFrequency: "આવૃત્તિ",
        medicineDuration: "અવધિ", medicineTiming: "સમય",
        medicineSideEffects: "આડ અસરો", medicineNo: "દવા",
        otcWarning: "⚠️ મહત્વપૂર્ણ: આ સામાન્ય OTC દવાઓની સૂચનાઓ છે. કોઈ પણ દવા લેતા પહેલા ડૉક્ટરની સલાહ લો.",
        dietRecommendations: "🥗 આહાર ભલામણો",
        dietSubtitle: "સ્વસ્થ થવામાં મદદ કરતા અને ટાળવા જોઈએ તેવા ખોરાક",
        foodsToEat: "ખાવા જોઈએ તેવા ખોરાક", foodsToAvoid: "ટાળવા જોઈએ તેવા ખોરાક",
        noSpecificRecommendations: "કોઈ ચોક્કસ ભલામણ નથી",
        noSpecificRestrictions: "કોઈ ચોક્કસ પ્રતિબંધ નથી",
        dietTip: "💡 સૂચન: પૂરતા પ્રવાહી સાથે સંતુલિત આહાર જાળવો.",
        safetyPrecautions: "🛡️ સુરક્ષા સાવચેતી",
        precautionsSubtitle: "ઝડપથી સ્વસ્થ થવા માટે મહત્વપૂર્ણ પગલાં",
        seekMedicalAttention: "⚠️ તાત્કાલિક તબીબી સહાય ક્યારે લેવી:",
        warnSymptomsWorsen: "લક્ષણો નોંધપાત્ર રીતે વધુ ખરાબ થઈ જાય",
        warnHighFever: "3 દિવસથી વધુ ઊંચો તાવ",
        warnBreathing: "શ્વાસ લેવામાં મુશ્કેલી અથવા છાતીમાં દુખાવો",
        warnDehydration: "ગંભીર ડિહાઇડ્રેશન", warnSuddenChange: "સ્થિતિમાં કોઈ અચાનક ફેરફાર",
        recoveryInformation: "⏱️ સ્વસ્થ થવાની માહિતી",
        recoverySubtitle: "અપેક્ષિત સમયરેખા અને ફોલો-અપ માર્ગદર્શન",
        expectedRecovery: "અપેક્ષિત સ્વસ્થ થવું", recoveryOutlook: "સ્વસ્થ થવાની સંભાવના",
        confidenceHigh: "ભલામણ કરેલ સારવાર સાથે સંપૂર્ણ સ્વસ્થ થવાની અપેક્ષા છે.",
        confidenceMedium: "યોગ્ય સંભાળ સાથે સારી સ્વસ્થ થવાની અપેક્ષા.",
        confidenceLow: "સ્વસ્થ થવા માટે તબીબી દેખરેખ જરૂરી હોઈ શકે.",
        recoveryTimeline: "સ્વસ્થ થવાની સમયરેખા",
        followUpRecommendations: "ફોલો-અપ ભલામણો",
        mostPatientsRecover: "મોટા ભાગના દર્દીઓ યોગ્ય સંભાળ સાથે સ્વસ્થ થઈ જાય છે.",
        medicalDisclaimer: "તબીબી અસ્વીકૃતિ",
        disclaimerText: "આ ફક્ત શૈક્ષણિક હેતુઓ માટે AI-સંચાલિત માર્ગદર્શન પ્રણાલી છે. આ વ્યાવસાયિક તબીબી સલાહનો વિકલ્પ નથી.",
        ex_fever: "તાવ, માથાનો દુખાવો, શરીરનો દુખાવો", ex_cough: "ઉધરસ, ગળાનો દુખાવો",
    },

    Punjabi: {
        ...commonKeys,
        title: "IAP-MG GenAI ਵਰਤ ਕੇ",
        welcomeBack: "ਵਾਪਸ ਸੁਆਗਤ ਹੈ", login: "ਲੌਗਇਨ", logout: "ਲੌਗਆਉਟ",
        welcomeBackUser: "ਵਾਪਸ ਸੁਆਗਤ ਹੈ, {name}",
        startNewDiagnosis: "ਨਵੀਂ ਜਾਂਚ ਸ਼ੁਰੂ ਕਰੋ",
        settings: "ਸੈਟਿੰਗਾਂ", changeLanguage: "ਭਾਸ਼ਾ ਬਦਲੋ",
        cancel: "ਰੱਦ ਕਰੋ", confirm: "ਪੁਸ਼ਟੀ ਕਰੋ",
        aiMedicalDiagnosis: "AI ਡਾਕਟਰੀ ਜਾਂਚ",
        possibleConditions: "ਸੰਭਾਵਿਤ ਸਥਿਤੀਆਂ",
        getAiDiagnosis: "AI ਜਾਂਚ ਪ੍ਰਾਪਤ ਕਰੋ",
        mostLikely: "ਸਭ ਤੋਂ ਸੰਭਾਵਿਤ", confidence: "ਭਰੋਸਾ",
        show: "ਦਿਖਾਓ", hide: "ਲੁਕਾਓ", clinicalReasoning: "ਕਲੀਨਿਕਲ ਤਰਕ",
        clickForBreakdown: "ਵੇਰਵਿਆਂ ਲਈ ਕਲਿੱਕ ਕਰੋ",
        confidenceBreakdown: "ਭਰੋਸੇ ਦਾ ਵੇਰਵਾ",
        howWeCalculated: "ਇਹ ਸਕੋਰ ਕਿਵੇਂ ਗਣਨਾ ਕੀਤਾ", overallScore: "ਕੁੱਲ ਭਰੋਸਾ ਸਕੋਰ",
        closeBreakdown: "ਬੰਦ ਕਰੋ", weight: "ਭਾਰ",
        scoreCalculationDesc: "AI ਨੇ 4 ਮੁੱਖ ਕਾਰਕਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਕੇ ਅੰਤਿਮ ਸਕੋਰ ਕੱਢਿਆ।",
        recommendedMedicines: "💊 ਸਿਫਾਰਿਸ਼ ਕੀਤੀਆਂ ਦਵਾਈਆਂ",
        medicinesSubtitle: "ਲੱਛਣਾਂ ਤੋਂ ਰਾਹਤ ਲਈ OTC ਦਵਾਈਆਂ (ਸਿਰਫ ਜਾਣਕਾਰੀ ਲਈ)",
        medicineDosage: "ਖੁਰਾਕ", medicineFrequency: "ਬਾਰੰਬਾਰਤਾ",
        medicineDuration: "ਅਵਧੀ", medicineTiming: "ਸਮਾਂ",
        medicineSideEffects: "ਮਾੜੇ ਪ੍ਰਭਾਵ", medicineNo: "ਦਵਾਈ",
        otcWarning: "⚠️ ਮਹੱਤਵਪੂਰਨ: ਇਹ ਸਾਧਾਰਨ OTC ਦਵਾਈਆਂ ਦੀਆਂ ਸੁਝਾਅ ਹਨ। ਕੋਈ ਵੀ ਦਵਾਈ ਲੈਣ ਤੋਂ ਪਹਿਲਾਂ ਡਾਕਟਰ ਦੀ ਸਲਾਹ ਲਓ।",
        dietRecommendations: "🥗 ਖੁਰਾਕ ਸਿਫਾਰਿਸ਼ਾਂ",
        dietSubtitle: "ਠੀਕ ਹੋਣ ਵਿੱਚ ਮਦਦ ਕਰਨ ਵਾਲੇ ਅਤੇ ਪਰਹੇਜ਼ ਕਰਨ ਵਾਲੇ ਖਾਣੇ",
        foodsToEat: "ਖਾਣ ਵਾਲੇ ਖਾਣੇ", foodsToAvoid: "ਪਰਹੇਜ਼ ਕਰਨ ਵਾਲੇ ਖਾਣੇ",
        noSpecificRecommendations: "ਕੋਈ ਖਾਸ ਸਿਫਾਰਿਸ਼ ਨਹੀਂ",
        noSpecificRestrictions: "ਕੋਈ ਖਾਸ ਪਾਬੰਦੀ ਨਹੀਂ",
        dietTip: "💡 ਸੁਝਾਅ: ਕਾਫੀ ਤਰਲ ਪਦਾਰਥਾਂ ਦੇ ਨਾਲ ਸੰਤੁਲਿਤ ਖੁਰਾਕ ਰੱਖੋ।",
        safetyPrecautions: "🛡️ ਸੁਰੱਖਿਆ ਸਾਵਧਾਨੀਆਂ",
        precautionsSubtitle: "ਜਲਦੀ ਠੀਕ ਹੋਣ ਲਈ ਮਹੱਤਵਪੂਰਨ ਕਦਮ",
        seekMedicalAttention: "⚠️ ਤੁਰੰਤ ਡਾਕਟਰੀ ਮਦਦ ਕਦੋਂ ਲੈਣੀ ਹੈ:",
        warnSymptomsWorsen: "ਲੱਛਣ ਕਾਫੀ ਵਿਗੜ ਜਾਂਦੇ ਹਨ",
        warnHighFever: "3 ਦਿਨਾਂ ਤੋਂ ਵੱਧ ਤੇਜ਼ ਬੁਖਾਰ",
        warnBreathing: "ਸਾਹ ਲੈਣ ਵਿੱਚ ਮੁਸ਼ਕਲ ਜਾਂ ਛਾਤੀ ਵਿੱਚ ਦਰਦ",
        warnDehydration: "ਗੰਭੀਰ ਡੀਹਾਈਡ੍ਰੇਸ਼ਨ", warnSuddenChange: "ਸਥਿਤੀ ਵਿੱਚ ਕੋਈ ਅਚਾਨਕ ਬਦਲਾਅ",
        recoveryInformation: "⏱️ ਠੀਕ ਹੋਣ ਦੀ ਜਾਣਕਾਰੀ",
        recoverySubtitle: "ਅਨੁਮਾਨਿਤ ਸਮਾਂ-ਰੇਖਾ ਅਤੇ ਫੌਲੋ-ਅੱਪ ਮਾਰਗਦਰਸ਼ਨ",
        expectedRecovery: "ਅਨੁਮਾਨਿਤ ਠੀਕ ਹੋਣਾ", recoveryOutlook: "ਠੀਕ ਹੋਣ ਦੀ ਸੰਭਾਵਨਾ",
        confidenceHigh: "ਸਿਫਾਰਿਸ਼ ਕੀਤੇ ਇਲਾਜ ਨਾਲ ਪੂਰੀ ਤਰ੍ਹਾਂ ਠੀਕ ਹੋਣ ਦੀ ਉਮੀਦ ਹੈ।",
        confidenceMedium: "ਸਹੀ ਦੇਖਭਾਲ ਨਾਲ ਚੰਗੀ ਤਰ੍ਹਾਂ ਠੀਕ ਹੋਣ ਦੀ ਉਮੀਦ।",
        confidenceLow: "ਠੀਕ ਹੋਣ ਲਈ ਡਾਕਟਰੀ ਨਿਗਰਾਨੀ ਦੀ ਲੋੜ ਹੋ ਸਕਦੀ ਹੈ।",
        recoveryTimeline: "ਠੀਕ ਹੋਣ ਦੀ ਸਮਾਂ-ਰੇਖਾ",
        followUpRecommendations: "ਫੌਲੋ-ਅੱਪ ਸਿਫਾਰਿਸ਼ਾਂ",
        mostPatientsRecover: "ਜ਼ਿਆਦਾਤਰ ਮਰੀਜ਼ ਸਹੀ ਦੇਖਭਾਲ ਨਾਲ ਇਸ ਸਮੇਂ ਵਿੱਚ ਠੀਕ ਹੋ ਜਾਂਦੇ ਹਨ।",
        medicalDisclaimer: "ਡਾਕਟਰੀ ਦਾਅਵਾ-ਰੱਦ",
        disclaimerText: "ਇਹ ਸਿਰਫ ਵਿੱਦਿਅਕ ਉਦੇਸ਼ਾਂ ਲਈ AI-ਸੰਚਾਲਿਤ ਮਾਰਗਦਰਸ਼ਨ ਪ੍ਰਣਾਲੀ ਹੈ। ਇਹ ਪੇਸ਼ੇਵਰ ਡਾਕਟਰੀ ਸਲਾਹ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ।",
        ex_fever: "ਬੁਖਾਰ, ਸਿਰਦਰਦ, ਸਰੀਰ ਦਰਦ", ex_cough: "ਖੰਘ, ਗਲੇ ਵਿੱਚ ਦਰਦ",
    },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(
        localStorage.getItem(STORAGE_KEYS?.LANGUAGE || 'preferred_language') || 'English'
    );

    const translate = (key, params = {}) => {
        let text = translations[language]?.[key] || translations['English']?.[key] || key;
        Object.entries(params).forEach(([k, v]) => { text = text.replace(`{${k}}`, v); });
        return text;
    };

    const changeLanguage = (newLang) => {
        if (translations[newLang]) {
            setLanguage(newLang);
            localStorage.setItem(STORAGE_KEYS?.LANGUAGE || 'preferred_language', newLang);
        }
    };

    const availableLanguages = Object.keys(translations).map(name => ({
        name,
        nativeName: {
            Telugu: 'తెలుగు', Hindi: 'हिन्दी', Tamil: 'தமிழ்', Kannada: 'ಕನ್ನಡ',
            Malayalam: 'മലയാളം', Marathi: 'मराठी', Bengali: 'বাংলা',
            Gujarati: 'ગુજરાતી', Punjabi: 'ਪੰਜਾਬੀ', English: 'English'
        }[name] || name
    }));

    return (
        <LanguageContext.Provider value={{ language, translate, changeLanguage, availableLanguages }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;